version: '3'

services:
  traefik:
    image: traefik:3.0
    command: --api.insecure=true --providers.docker
    volumes:
      - /Users/engels/.docker/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"

  webapp1:
    image: containous/whoami
    labels:
      - "traefik.http.routers.webapp1.rule=Host(`app1.localhost`)"
    command:
      - "--name=app1"

  webapp2:
    image: containous/whoami
    labels:
      - "traefik.http.routers.webapp2.rule=Host(`app2.localhost`)"
    command: 
      - "--name=app2"