version: '3'
services:
  traefik:
    image: "traefik:v2.0.0"
    restart: always
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --log.level=DEBUG
      #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.email=suporte@infopublic.com.br
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`admdashboard.infopublic.com.br`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  pjsuporte:
    image: esouza99/pjsuporte:1.1
    labels:
      - "traefik.http.routers.app.rule=Host(`suporte.infopublic.com.br`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
    expose:
      - 8000
    env_file:
      - .env
    links:
      - dados:dbserver
    restart: always
    depends_on:
      - dados

  dados:
    image: mariadb:latest
    env_file:
      - .env-dados
    ports:
      - "8001:3306"
    volumes:
      - "dados:/var/lib/mysql"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  dados:
