version: '3'

services:
  traefik:
    image: traefik:3.0
    command: 
      - "--api.insecure=true" 
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mongo-network
    ports:
      - "80:80"
      - "8080:8080"
        
  mongo-express:
    image: mongo-express
    labels:
      - "traefik.http.routers.mongo-express.rule=Host(`mongo-express.infopublic.com.br`)"
      - "traefik.http.routers.mongo-express.entrypoints=web"
    networks:
      - mongo-network
    ports:
      - "8081"
    links:
      - "mongodb:database"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: "infopublicpb"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "Eredopor5318"
      ME_CONFIG_BASICAUTH_USERNAME: "infopublicpb"
      ME_CONFIG_BASICAUTH_PASSWORD: "Eredopor5318"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "infopublicpb"
      MONGO_INITDB_ROOT_PASSWORD: "Eredopor5318"
    volumes:
      - "mongo-teste:/data/db"
      - "mongoteste-configdb:/data/configdb"
    ports:
      - "27017:27017"
    networks:
      - mongo-network

volumes:
  mongo-teste:
  mongoteste-configdb:

networks:
  mongo-network:
