version: '3'

services:
  traefik:
    image: traefik:3.0
    command: 
      #- "--api.insecure=true" 
      - "--providers.docker"
      #- "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=suporte@infopublic.com"
      - "--certificatesresolvers.myresolver.acme.storage=/opt/letsencrypt/acme.json"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/letsencrypt:/opt/letsencrypt
    networks:
      - mongo-network
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    ports:
      - "80:80"
      - "443:443"
        
  mongo-express:
    image: mongo-express
    labels:
      - "traefik.http.routers.mongo-express.rule=Host(`mongo-express.infopublic.com.br`)"
      - "traefik.http.routers.mongo-express.entrypoints=websecure"
      - "traefik.http.routers.mongo-express.tls=true"
      - "traefik.http.routers.mongo-express.tls.certresolver=myresolver"
    networks:
      - mongo-network
    ports:
      - "8081"
    links:
      - "mongodb:database"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: "example"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"
      ME_CONFIG_BASICAUTH_USERNAME: "example"
      ME_CONFIG_BASICAUTH_PASSWORD: "example"

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "example"
      MONGO_INITDB_ROOT_PASSWORD: "example"
    volumes:
      - "mongo-teste:/data/db"
      - "mongoteste-configdb:/data/configdb"
    ports:
      - "27017:27017"
    networks:
      - mongo-network

volumes:
  mongo-teste:
  mongoteste-configdb:

networks:
  mongo-network:

