version: '3'

services:
  traefik:
    image: traefik:3.0
    command: 
      - "--providers.docker"
      #- "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=suporte@infopublic.com"
      - "--certificatesresolvers.myresolver.acme.storage=/opt/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/opt/letsencrypt:/opt/letsencrypt"
    ports:
      - "80:80"
      - "443:443"

  webapp1:
    image: containous/whoami
    labels:
      - "traefik.http.routers.webapp1.rule=Host(`teste.infopublic.com.br`)"
      #- "traefik.http.routers.webapp1.entrypoints=websecure"
      #- "traefik.http.routers.webapp1.tls.certresolver=myresolver"
    command:
      - "--name=app1"

  webapp2:
    image: containous/whoami
    labels:
      - "traefik.http.routers.webapp2.rule=Host(`spot.infopublic.com.br`)"
      #- "traefik.http.routers.webapp2.entrypoints=websecure"
      #- "traefik.http.routers.webapp2.tls.certresolver=myresolver"
    command: 
      - "--name=app2"